[gcp_service_account]
type = "service_account"
project_id = "striped-option-457013-a9"
private_key_id = "33a5cb342014a7c40892df14f9e75de9d98aa684"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCi+NkcI0fopglL
CQav10QhhFWyow614Nkw3oyQaKPzDjjq++TMuGRqG31stmllnZ9QJiX2ubQjATYb
zen6c+p8MXA1+ek87TtHFxZPN/WxUeRBKEEVAtBQFGoUyB/RJGd6ZKyGg/v+EQE6
oe3dFPEFHRIITFZITwudafG0PwO2YbUnkipKrQ4i4ytudP0spWFOm32+cRMiQ2zh
p30wmWDuk3N6YNM4iFvpiWtWmacj+owUpuadollG1Eq7yKeeo267iMS06Zx8Tdnp
cxEnrbeYVZvAe1USoWy61JQ5aWtTkl0ltnV7VCX6lgE1z57nvtrGPOcQqJntbsLd
yiIkIpHDAgMBAAECggEAGoCQQeik3Xr+wOKHYVoG3NJ54zJsBny5pR5TynoRy0lR
TTlIVFhaD/1HcMHbMuimizCg9NXvKtAcHfpm5dEq3SZnAogQ+1Ty0lU5TgmiHUNd
dJEYwFN0T8l6FMYUknyyjS9I9RkKhh76za+ekFjC9xtqnsnXMCwWjfM4GKE0t9g5
77XtCyphLi8wXO9u6O75Vp6eeH8waitJWM8YZXaSbtSyDabKUkmP6hduds3gia4C
yFu8tM+c3H2sWF/4nFls7HP3yInGAxnh+vux36rejiG0i41tUYsuF3l6Z8t9wb/O
H42eTs2JUA9hxCUvvAS5vutceh4OGNjqkQyYgJu3fQKBgQDlIVfrNHgcSy1cxUea
LF3joVUcOHNTVwJKTd/zTxM54IwY+roL6XDhvnULnDZK9Rb6LDcp8fwA2nelexbt
xq+70t7fODoYo12vQmRbmn97Jnxvzhn0HXhyRJ7FqGa6ISumpww5CSgZD58V6VLC
DR3e+A/mXJKIgtpFSKqvSWH7jwKBgQC2FWNKpoZRfcSdZ046BmtY4xH3OrHVhid7
CwHeJ+3mdCAY+VgD+KHX4ZFvotb2liP4XwOO+FcMk1vL9fhuWdrOkk/iqht2bEJg
E+QKOkFpR3tOh8PzVxSLqa9LT6QMsp82ZWbHCPQRTJ2jefW/3kHFfcCKPwVVHvBP
wIAO9bK8jQKBgB/MQ85BZtXOXQo92pT7yT/Y2N3ku6R6M7gqHIVAmRN0JR0mVoFm
sSKy8r1cvXAjmT+4uSMaEPXxW59ceK8g3qx7NDDYNb/LlCnJVfIce8qUabp+aL2n
BVseSMZ3e2IjTlJ/ZkPYEHeB4nsA+Voyxc12sYYvnKpTNoVc80sGLRHjAoGAEcPA
bjYVALpehmTf0vVxX7i3tgE5/HUcQPrv8ba/lS5bO1SIa8rEL4XIZLXkdyZq1/6d
IEPGammuGRYkaM/Hc0P/G0QxbbpeN3V5WC4a16SruRux2Hn0fTPO8HASt1JuCiaW
gnCzL0TkVGC/wzpx/EyqjlJbuNRN6doEJHGAQLkCgYB6P0XeCUhBVdOreOtE8c2Q
+UF0s46tsPx+aHQdUX+UnFLoqjBYv6/+eUuEsihNzc3u5aOPi+KNhPuPwH3Q/K12
74xhyEc31/fbf2rlyiIzei7zIHFyhpdmO/LOBlp13hazbAVeXU0DoEPefoMjH802
HMdj/FmQEjQ4+ZpqHBaCCg==
-----END PRIVATE KEY-----"""
client_email = "aurum-wcs@striped-option-457013-a9.iam.gserviceaccount.com"
client_id = "102590607068075744919"
token_uri = "https://oauth2.googleapis.com/token"
